### ISSUE TITLE
Marketplace Frontend: Shop Pack cover image not scaling proportionally

### ISSUE THREAD

**Issue by babsgosgens** [gameserverapp/Platform#991]
Shoppack images are stretched to their container width, distorting the image:
![image](https://github.com/user-attachments/assets/46b0f469-0148-4346-a608-225318a0d7b3)

Adding an object-fit will mitigate this:
```css
.marketplace__show__header__img {
    display: block;
    height: 500px;
    width: 100%;
    object-fit: contain;
}
```

You could also consider moving the both the `width` and `display` declaration from the image, and add `text-align: center` on the parent div container. This will align the image again.

![image](https://github.com/user-attachments/assets/e9679c0b-5379-496e-9966-f5f473af38b2)

https://dash.gameserverapp.com/marketplace/market/shop_pack_group/4
